import './globals.css';
import type { Metadata } from 'next';
import { StyledEngineProvider } from '@mui/material/styles';
import Navbar from '@/components/Navbar';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <StyledEngineProvider injectFirst>
        <body className={inter.className}>
          <Navbar />
          <main className="flex flex-col">{children}</main>
        </body>
      </StyledEngineProvider>
    </html>
  );
}
